import type { Metadata } from "next";
import "./globals.css";
import ScrollSmooth from "../components/fragments/scroll-smooth"
// import { fontSofia, fontSpace } from "@/lib/fonts";


export const metadata: Metadata = {
  title: "Riko Fernanda Saputra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <ScrollSmooth>
        {children}
        </ScrollSmooth>
      </body>
    </html>
  );
}
